version: '3'

services:

  jenkins:
    image: gerritforge/jw2017-jenkins
    environment:
     - GIT_USER=jenkins
     - GIT_PASSWORD=secret
     - GIT_SERVER_URL=http://gerrit:8080/gerritforge/play-scala-chatroom-example
     - JENKINS_URL=http://jenkins-pipeline
     - RABBITMQ_DEFAULT_USER=user
     - RABBITMQ_DEFAULT_PASS=password
    volumes:
     - jenkins-volume:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    depends_on: 
     - gerrit
     - rabbitmq
    networks:
     - local-network

  nginx:
    image: gerritforge/jw2017-nginx
    ports:
     - "80:80"
    networks:
     - local-network

  gerrit:
    image: gerritforge/jw2017-gerrit
    networks:
     - local-network
    depends_on:
     - rabbitmq
    volumes:
     - git-volume:/var/gerrit/git
     - db-volume:/var/gerrit/db
     - index-volume:/var/gerrit/index
    ports:
     - "29418:29418"

  rabbitmq:
    image: gerritforge/jw2017-rabbitmq
    networks:
     - local-network
    environment:
     - RABBITMQ_DEFAULT_USER=user
     - RABBITMQ_DEFAULT_PASS=password
    ports:
     - "15672:15672"
     - "5672:5672"

networks:
    local-network:
        driver: bridge

volumes:
    jenkins-volume:
    git-volume:
    db-volume:
    index-volume:
